/**
 * YouTube Transcript Extractor - Cloudflare Worker
 *
 * Serves a mobile-friendly page at GET / where you paste a YouTube URL and
 * get back the video's transcript (plain text or with timestamps), ready to
 * copy or download and drop into a doc for podcast/blog work.
 *
 * POST /api/transcript { url } does the actual work server-side (YouTube's
 * caption endpoints don't send CORS headers, so this can't run purely in the
 * browser - the Worker is the fetch-on-your-behalf piece).
 *
 * POST /api/save-to-drive { filename, text } optionally relays a transcript
 * to a small Google Apps Script "bridge" (see README) which drops it into a
 * Google Drive folder. Configured via the APPS_SCRIPT_URL and
 * APPS_SCRIPT_TOKEN Worker secrets - if unset, the button just reports
 * Drive isn't connected yet rather than failing the whole app.
 */

const USER_AGENT =
  "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36";

export default {
  async fetch(request, env) {
    const url = new URL(request.url);

    if (url.pathname === "/api/transcript" && request.method === "POST") {
      return handleTranscriptRequest(request);
    }

    if (url.pathname === "/api/save-to-drive" && request.method === "POST") {
      return handleSaveToDrive(request, env);
    }

    if (url.pathname === "/" || url.pathname === "/index.html") {
      return new Response(PAGE_HTML, {
        headers: { "content-type": "text/html; charset=utf-8" },
      });
    }

    return new Response("Not found", { status: 404 });
  },
};

async function handleSaveToDrive(request, env) {
  try {
    if (!env.APPS_SCRIPT_URL || !env.APPS_SCRIPT_TOKEN) {
      return jsonError(
        "Google Drive isn't connected yet - set the APPS_SCRIPT_URL and APPS_SCRIPT_TOKEN Worker secrets (see README's Drive section)."
      );
    }
    const { filename, text } = await request.json();
    if (!text) return jsonError("No transcript text to save.");
    const safeName = (filename || "transcript").replace(/[^a-z0-9\-_. ]+/gi, "-").slice(0, 120);

    const res = await fetch(env.APPS_SCRIPT_URL, {
      method: "POST",
      headers: { "content-type": "application/json" },
      body: JSON.stringify({
        token: env.APPS_SCRIPT_TOKEN,
        filename: safeName,
        text,
      }),
      redirect: "follow",
    });
    const data = await res.json();
    if (data.error) return jsonError(`Google Drive save failed: ${data.error}`);

    return new Response(JSON.stringify({ link: data.link }), {
      headers: { "content-type": "application/json" },
    });
  } catch (err) {
    return jsonError(`Drive save failed: ${err.message || err}`);
  }
}

async function handleTranscriptRequest(request) {
  try {
    const { url: videoUrl, lang } = await request.json();
    const videoId = extractVideoId(videoUrl);
    if (!videoId) {
      return jsonError("Couldn't find a video ID in that URL. Paste a full YouTube link (or just the 11-character video ID).");
    }

    const watchHtml = await fetchWatchPage(videoId);
    const playerResponse = extractPlayerResponse(watchHtml);
    if (!playerResponse) {
      return jsonError("YouTube didn't return the expected page data. The video may be unavailable, or YouTube changed its page format.");
    }

    const status = playerResponse?.playabilityStatus?.status;
    if (status && status !== "OK") {
      const reason = playerResponse?.playabilityStatus?.reason || status;
      return jsonError(`This video isn't accessible for transcript extraction: ${reason}`);
    }

    const tracks =
      playerResponse?.captions?.playerCaptionsTracklistRenderer?.captionTracks;
    if (!tracks || tracks.length === 0) {
      return jsonError("This video has no captions/transcript available.");
    }

    const track = pickTrack(tracks, lang || "en");
    const segments = await fetchAndParseTranscript(track.baseUrl);

    return new Response(
      JSON.stringify({
        title: playerResponse?.videoDetails?.title || "Untitled video",
        videoId,
        language: track.languageCode,
        isAutoGenerated: track.kind === "asr",
        availableLanguages: tracks.map((t) => ({
          code: t.languageCode,
          name: t.name?.simpleText || t.name?.runs?.[0]?.text || t.languageCode,
          auto: t.kind === "asr",
        })),
        segments,
      }),
      { headers: { "content-type": "application/json" } }
    );
  } catch (err) {
    return jsonError(`Something went wrong: ${err.message || err}`);
  }
}

function jsonError(message) {
  return new Response(JSON.stringify({ error: message }), {
    status: 400,
    headers: { "content-type": "application/json" },
  });
}

function extractVideoId(input) {
  if (!input) return null;
  const trimmed = input.trim();
  if (/^[a-zA-Z0-9_-]{11}$/.test(trimmed)) return trimmed;
  try {
    const u = new URL(trimmed);
    if (u.hostname === "youtu.be") return u.pathname.slice(1, 12);
    if (u.pathname.startsWith("/shorts/")) return u.pathname.split("/")[2];
    if (u.pathname.startsWith("/embed/")) return u.pathname.split("/")[2];
    if (u.searchParams.has("v")) return u.searchParams.get("v");
  } catch {
    // not a URL, fall through
  }
  return null;
}

async function fetchWatchPage(videoId) {
  const res = await fetch(`https://www.youtube.com/watch?v=${videoId}&hl=en`, {
    headers: {
      "User-Agent": USER_AGENT,
      "Accept-Language": "en-US,en;q=0.9",
    },
  });
  return res.text();
}

function extractPlayerResponse(html) {
  const marker = "ytInitialPlayerResponse";
  const markerIdx = html.indexOf(marker);
  if (markerIdx === -1) return null;
  const jsonStr = extractBalancedJSON(html, markerIdx);
  if (!jsonStr) return null;
  try {
    return JSON.parse(jsonStr);
  } catch {
    return null;
  }
}

/** Scans forward from `startIndex` for the first `{...}` object, respecting
 * quoted strings so braces inside strings don't throw off the depth count. */
function extractBalancedJSON(text, startIndex) {
  let depth = 0;
  let start = -1;
  let inString = false;
  let stringChar = "";
  let escape = false;

  for (let i = startIndex; i < text.length; i++) {
    const ch = text[i];
    if (start === -1) {
      if (ch === "{") {
        start = i;
        depth = 1;
      }
      continue;
    }
    if (escape) {
      escape = false;
      continue;
    }
    if (ch === "\\") {
      escape = true;
      continue;
    }
    if (inString) {
      if (ch === stringChar) inString = false;
      continue;
    }
    if (ch === '"' || ch === "'") {
      inString = true;
      stringChar = ch;
      continue;
    }
    if (ch === "{") depth++;
    else if (ch === "}") {
      depth--;
      if (depth === 0) return text.slice(start, i + 1);
    }
  }
  return null;
}

function pickTrack(tracks, preferredLang) {
  const manualIn = (lang) => tracks.find((t) => t.languageCode === lang && t.kind !== "asr");
  const anyIn = (lang) => tracks.find((t) => t.languageCode === lang);
  return (
    manualIn(preferredLang) ||
    anyIn(preferredLang) ||
    tracks.find((t) => t.kind !== "asr") ||
    tracks[0]
  );
}

async function fetchAndParseTranscript(baseUrl) {
  const res = await fetch(baseUrl, {
    headers: { "User-Agent": USER_AGENT },
  });
  const xml = await res.text();
  const segments = [];
  const re = /<text start="([\d.]+)" dur="([\d.]+)"[^>]*>([\s\S]*?)<\/text>/g;
  let m;
  while ((m = re.exec(xml)) !== null) {
    const text = decodeEntities(m[3]).replace(/\s+/g, " ").trim();
    if (!text) continue;
    segments.push({ start: parseFloat(m[1]), dur: parseFloat(m[2]), text });
  }
  return segments;
}

function decodeEntities(str) {
  return str
    .replace(/&amp;/g, "&")
    .replace(/&lt;/g, "<")
    .replace(/&gt;/g, ">")
    .replace(/&quot;/g, '"')
    .replace(/&#39;/g, "'")
    .replace(/&#(\d+);/g, (_, code) => String.fromCharCode(parseInt(code, 10)));
}

const PAGE_HTML = `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>YouTube Transcript Extractor</title>
<style>
  :root {
    color-scheme: light dark;
    --bg: #f5f5f7;
    --card: #ffffff;
    --text: #1a1a1a;
    --muted: #6b6b6b;
    --border: #ddd;
    --accent: #c4302b;
    --accent-text: #fff;
  }
  @media (prefers-color-scheme: dark) {
    :root {
      --bg: #121212;
      --card: #1e1e1e;
      --text: #f0f0f0;
      --muted: #a0a0a0;
      --border: #333;
    }
  }
  * { box-sizing: border-box; }
  body {
    margin: 0;
    font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;
    background: var(--bg);
    color: var(--text);
    padding: 16px;
  }
  .wrap { max-width: 720px; margin: 0 auto; }
  h1 { font-size: 1.3rem; margin: 0 0 4px; }
  p.sub { color: var(--muted); margin: 0 0 20px; font-size: 0.9rem; }
  .card {
    background: var(--card);
    border: 1px solid var(--border);
    border-radius: 12px;
    padding: 16px;
    margin-bottom: 16px;
  }
  input[type=text] {
    width: 100%;
    padding: 12px;
    font-size: 16px;
    border: 1px solid var(--border);
    border-radius: 8px;
    background: var(--bg);
    color: var(--text);
  }
  button {
    font-size: 16px;
    padding: 12px 16px;
    border-radius: 8px;
    border: none;
    cursor: pointer;
    font-weight: 600;
  }
  .btn-primary {
    background: var(--accent);
    color: var(--accent-text);
    width: 100%;
    margin-top: 10px;
  }
  .btn-primary:disabled { opacity: 0.6; }
  .btn-row { display: flex; flex-wrap: wrap; gap: 8px; margin-top: 12px; }
  .btn-row button {
    flex: 1 1 auto;
    background: var(--bg);
    color: var(--text);
    border: 1px solid var(--border);
  }
  #status { margin-top: 10px; font-size: 0.9rem; color: var(--muted); min-height: 1.2em; }
  #driveStatus { margin-top: 8px; font-size: 0.85rem; color: var(--muted); min-height: 1.2em; }
  #driveStatus a { color: var(--text); }
  #error { color: var(--accent); font-size: 0.9rem; margin-top: 10px; display: none; }
  #result { display: none; }
  #meta { font-size: 0.9rem; color: var(--muted); margin-bottom: 10px; }
  textarea {
    width: 100%;
    min-height: 40vh;
    font-size: 15px;
    line-height: 1.5;
    padding: 12px;
    border: 1px solid var(--border);
    border-radius: 8px;
    background: var(--bg);
    color: var(--text);
    resize: vertical;
  }
  label.toggle {
    display: flex;
    align-items: center;
    gap: 8px;
    font-size: 0.9rem;
    color: var(--muted);
    margin-bottom: 10px;
  }
</style>
</head>
<body>
<div class="wrap">
  <h1>YouTube Transcript Extractor</h1>
  <p class="sub">Paste a video link, get the transcript, copy it into your podcast/blog notes.</p>

  <div class="card">
    <input type="text" id="urlInput" placeholder="https://www.youtube.com/watch?v=..." inputmode="url" autocapitalize="off" autocorrect="off">
    <button class="btn-primary" id="fetchBtn">Get Transcript</button>
    <div id="status"></div>
    <div id="error"></div>
  </div>

  <div class="card" id="result">
    <div id="meta"></div>
    <label class="toggle"><input type="checkbox" id="timestampToggle"> Show timestamps</label>
    <textarea id="transcriptOut" readonly></textarea>
    <div class="btn-row">
      <button id="copyBtn">Copy</button>
      <button id="downloadTxtBtn">Download .txt</button>
      <button id="saveDriveBtn">Save to Drive</button>
    </div>
    <div id="driveStatus"></div>
  </div>
</div>

<script>
  const urlInput = document.getElementById('urlInput');
  const fetchBtn = document.getElementById('fetchBtn');
  const statusEl = document.getElementById('status');
  const errorEl = document.getElementById('error');
  const resultEl = document.getElementById('result');
  const metaEl = document.getElementById('meta');
  const out = document.getElementById('transcriptOut');
  const timestampToggle = document.getElementById('timestampToggle');
  const copyBtn = document.getElementById('copyBtn');
  const downloadTxtBtn = document.getElementById('downloadTxtBtn');
  const saveDriveBtn = document.getElementById('saveDriveBtn');
  const driveStatus = document.getElementById('driveStatus');

  let lastData = null;

  function formatTime(sec) {
    const m = Math.floor(sec / 60);
    const s = Math.floor(sec % 60);
    return m + ':' + String(s).padStart(2, '0');
  }

  function render() {
    if (!lastData) return;
    const withTs = timestampToggle.checked;
    out.value = lastData.segments
      .map(seg => withTs ? '[' + formatTime(seg.start) + '] ' + seg.text : seg.text)
      .join(withTs ? '\\n' : ' ');
  }

  timestampToggle.addEventListener('change', render);

  fetchBtn.addEventListener('click', async () => {
    const url = urlInput.value.trim();
    if (!url) return;
    errorEl.style.display = 'none';
    resultEl.style.display = 'none';
    fetchBtn.disabled = true;
    statusEl.textContent = 'Fetching transcript...';
    try {
      const res = await fetch('/api/transcript', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ url })
      });
      const data = await res.json();
      if (!res.ok) throw new Error(data.error || 'Unknown error');
      lastData = data;
      metaEl.textContent = data.title + (data.isAutoGenerated ? ' (auto-generated captions)' : '') + ' — ' + data.segments.length + ' segments';
      render();
      resultEl.style.display = 'block';
      statusEl.textContent = '';
      driveStatus.textContent = '';
    } catch (err) {
      errorEl.textContent = err.message;
      errorEl.style.display = 'block';
      statusEl.textContent = '';
    } finally {
      fetchBtn.disabled = false;
    }
  });

  copyBtn.addEventListener('click', async () => {
    await navigator.clipboard.writeText(out.value);
    copyBtn.textContent = 'Copied!';
    setTimeout(() => copyBtn.textContent = 'Copy', 1500);
  });

  downloadTxtBtn.addEventListener('click', () => {
    const blob = new Blob([out.value], { type: 'text/plain' });
    const a = document.createElement('a');
    a.href = URL.createObjectURL(blob);
    const safeTitle = (lastData?.title || 'transcript').replace(/[^a-z0-9]+/gi, '-').slice(0, 60);
    a.download = safeTitle + '.txt';
    a.click();
    URL.revokeObjectURL(a.href);
  });

  saveDriveBtn.addEventListener('click', async () => {
    if (!lastData) return;
    const safeTitle = (lastData.title || 'transcript').replace(/[^a-z0-9]+/gi, '-').slice(0, 60);
    saveDriveBtn.disabled = true;
    driveStatus.textContent = 'Saving to Drive...';
    try {
      const res = await fetch('/api/save-to-drive', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ filename: safeTitle, text: out.value })
      });
      const data = await res.json();
      if (!res.ok) throw new Error(data.error || 'Unknown error');
      driveStatus.innerHTML = 'Saved to Drive — <a href="' + data.link + '" target="_blank" rel="noopener">open file</a>';
    } catch (err) {
      driveStatus.textContent = 'Drive save failed: ' + err.message;
    } finally {
      saveDriveBtn.disabled = false;
    }
  });

  urlInput.addEventListener('keydown', (e) => {
    if (e.key === 'Enter') fetchBtn.click();
  });
</script>
</body>
</html>
`;
